name: 'Hello World'
description: 'Autotag'
runs:
  using: "composite"
  steps:
    - run: git log > git_log.txt
      shell: bash
    - run: node ${{ github.action_path }}/parse_log.js
      shell: bash