name: 'Autotag'
description: 'Autotag repository based on #major, #minor, #patch commit messages'
inputs:
  doit:  # id of input
    description: 'Wheather to really to the tagging or not, just to obtain the tag to be applied but not applying it'
    required: false
    default: true
outputs:
  newtag:
    description: "New tag generated"
    value: ${{ steps.output-newtag.outputs.newtag }}
runs:
  using: "composite"
  steps:
    # dummy files
    - run: touch commands.txt
      shell: bash
    - run: echo "newtag=none" > newtag.txt
      shell: bash
    # get logs in compact form to extract the #major, #minor, #patch labels
    - run: git log --decorate=full --pretty=oneline >  git_log.txt
      shell: bash
    # calculate next tag
    - run: node ${{ github.action_path }}/parse_log.js
      shell: bash
    - run: cat newtag.txt >> $GITHUB_OUTPUT
      id: output-newtag
      shell: bash
    # apply new tag
    - run: bash commands.txt
      shell: bash
      if: github.event.inputs.doit