name: 'Hello World'
description: 'Autotag'
runs:
  using: "composite"
  steps:
    # dummy file
    - run: touch commands.txt
      shell: bash
    # get logs in compact form to extract the #major, #minor, #patch labels
    - run: git log --decorate=full --pretty=oneline >  git_log.txt
      shell: bash
    # calculate next tag
    - run: node ${{ github.action_path }}/parse_log.js
      shell: bash
    # apply new tag
    - run: bash commands.txt
      shell: bash